[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.bcmath",
  "php82Extensions.curl",
  "php82Extensions.openssl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "nodejs_22",
  "npm"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "rm -rf public/build",

  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan cache:clear",

  "npm run build",

  "php artisan storage:link"
]

[start]
cmd = "frankenphp php-server -r public -p $PORT"
