[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_pgsql"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
